Add circuit template how-to topic
Cargill/splinter-docs pull request #160
Opened 2020-10-05 20:13 UTC by shannynalayna

Adds an app-dev guide using the `circuit-template` feature in Splinter

2020-10-06 15:26 UTC, peterschwarz requested changes

2020-10-06 15:26 UTC, peterschwarz commented on docs/0.5/howto/using_circuit_templates.md
> +A circuit template contains a set of `rule`s which partially define a new circuit.
I don't think that rule needs to be in code-quotes.

2020-10-06 15:26 UTC, peterschwarz commented on docs/0.5/howto/using_circuit_templates.md
> +There are three main sections to the circuit template, `version`, `arg`s, and
These don't match what's in the example: they should be `version`, `args`, and `rules`.  The same is true throughout the rest of the docs on these sections.

2020-10-06 15:26 UTC, peterschwarz commented on docs/0.5/howto/using_circuit_templates.md
> +## Rules
In this section, I would remove much of the code quotes, except when directly referring to the `rules` section.  Each individual thing is a "rule", but it is not a code term that anyone uses when constructing a template.

2020-10-06 15:26 UTC, peterschwarz commented on docs/0.5/howto/using_circuit_templates.md
> +‘:’. Using multiple directories does have an effect on the behavior of the
Was the intent to make this a code-quoted `:`?

2020-10-06 15:50 UTC, vaporos commented on docs/0.5/howto/using_circuit_templates.md
> +```
I think if you do ```yaml here you will see syntax highlighting.

2020-10-06 15:51 UTC, vaporos commented on docs/0.5/howto/using_circuit_templates.md
> +This describes the version of circuit the template is targeting.
This is the version of the template file, not the version of the circuit.

2020-10-06 19:55 UTC, peterschwarz reviewed
Is this document intended to enumerate the available rules?  Or is that in a separate document?

2020-10-08 20:19 UTC, peterschwarz approved these changes

2020-10-08 22:45 UTC, vaporos approved these changes

2020-10-09 12:44 UTC, merged