Update man page index
Cargill/splinter-docs pull request #206
Opened 2021-04-15 19:50 UTC by vaporos

Adds all man pages that exist but where not previously in the index -- including experimental subcommands.

2021-04-16 20:26 UTC, agunde406 requested changes

2021-04-16 20:26 UTC, agunde406 commented on docs/0.5/references/cli/index.md
> +### Registry managment
managment -> management

2021-04-19 14:20 UTC, vaporos commented on docs/0.5/references/cli/index.md
> +### Registry managment
Fixed

2021-04-19 14:22 UTC, agunde406 approved these changes

2021-06-14 14:29 UTC, rbuysse approved these changes

2021-06-14 14:29 UTC, peterschwarz approved these changes

2021-06-14 14:30 UTC, merged