Update Biome User Management
Cargill/splinter-docs pull request #278
Opened 2021-11-30 18:03 UTC by isabeltomb

Update the Biome User Management 0.5 docs
- update content to reflect the current submodules in the biome module and the current biome REST API endpoints
- add an updated diagram for the biome database tables

2021-11-30 18:06 UTC, vaporos requested changes
Should keep this an svg

2021-11-30 18:30 UTC, isabeltomb commented
> Should keep this an svg

New diagram is now svg

2021-12-09 21:57 UTC, peterschwarz approved these changes

2021-12-09 22:21 UTC, peterschwarz submitted a review, later dismissed

2021-12-16 16:54 UTC, vaporos approved these changes

2021-12-17 17:05 UTC, peterschwarz approved these changes

2021-12-17 17:06 UTC, merged