Add a Grid backwards compatibility test
Cargill/splinter-docs pull request #289
Opened 2021-12-22 18:21 UTC by agunde406

This is the process that has been used to verify that
Grid and Splinter 0.4 and Splinter 0.6 are compatible.
This process is put up with all current hacks to be able
to do the test locally (instead of requiring docker).
In the future this hacks may not be required.

Signed-off-by: Andrea Gunderson <agunde@bitwise.io>

2022-01-04 16:32 UTC, vaporos commented
How about making the left sidebar read 'Testing' and then we have a page that includes this content and some very high-level content about running LR networks?

2022-01-04 20:16 UTC, agunde406 commented
> How about making the left sidebar read 'Testing' and then we have a page that includes this content and some very high-level content about running LR networks?

Sure I will work on that

2022-01-05 14:58 UTC, isabeltomb approved these changes

2022-01-05 17:01 UTC, rbuysse requested changes

2022-01-05 17:57 UTC, agunde406 commented on releases/0.6/testing.md
> +> Requires rust and docker
I'm not sure what minimum version would actual be required for rust but I can put the version that I tested it on.

2022-01-05 18:12 UTC, agunde406 commented on releases/0.6/testing.md
> +and state data, cleans up log and state from the previous run and finally
fixed

2022-01-05 18:12 UTC, agunde406 commented on releases/0.6/testing.md
> +and one three-party scabbard circuit are established, resulting in one node
fixed

2022-01-05 18:12 UTC, agunde406 commented on releases/0.6/testing.md
> +[manpage](https://github.com/hyperledger/transact/blob/main/cli/man/transact-workload.1.md).
fixed

2022-01-05 18:13 UTC, agunde406 commented on releases/0.6/testing.md
> +docs/0.6/troubleshooting/checking_state_consistency.md %})
fixed

2022-01-05 18:13 UTC, agunde406 commented on releases/0.6/testing.md
> +the following 0.4 compatible circuit proposal
fixed

2022-01-05 18:37 UTC, rbuysse approved these changes

2022-01-05 21:03 UTC, isabeltomb approved these changes

2022-01-07 16:45 UTC, merged